apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
spec:
  rules:
  - host: sam.com
    http:
      paths:
      - path: /service-1
        backend:
          serviceName: auth
          servicePort: 50
      - path: /service-2
        backend:
          serviceName: product
          servicePort: 80
      - path: /service-3
        backend:
          serviceName: order
          servicePort: 90
