apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: ecomerce-ingress

  annotations:


    
    kubernetes.io/ingress.class: nginx

spec:

  ingressClassName: nginx-example

  rules:

  - http:

      paths:

      - path: /order

        pathType: Prefix

        backend:

          service:

            name: order-service

            port:

              number: 8080
